# Generated by Django 4.0.dev20210713072537 on 2021-08-24 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_word', models.CharField(max_length=30)),
                ('Second_word', models.CharField(max_length=30)),
                ('Third_word', models.CharField(max_length=30)),
                ('Fourth_word', models.CharField(max_length=30)),
                ('Sentence', models.TextField(max_length=150)),
                ('Difficulty', models.CharField(max_length=5)),
                ('pub_date', models.DateTimeField(null=True, verbose_name=datetime.datetime(2021, 8, 24, 12, 43, 1, 589809, tzinfo=utc))),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='hebrew_words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=40)),
                ('meaning', models.CharField(max_length=40)),
                ('Sentence', models.TextField(max_length=60)),
                ('pub_date', models.DateTimeField(null=True, verbose_name=datetime.datetime(2021, 8, 24, 12, 43, 1, 589809, tzinfo=utc))),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
