# Generated by Django 4.0.dev20210713072537 on 2021-08-24 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('English_word', models.CharField(max_length=30, unique=True)),
                ('Hebrew_word', models.CharField(max_length=30)),
                ('How_To_Remember', models.TextField(max_length=60)),
                ('Name', models.CharField(max_length=20, null=True)),
                ('pub_date', models.DateTimeField(null=True, verbose_name=datetime.datetime(2021, 8, 24, 12, 43, 1, 588808, tzinfo=utc))),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
