# Generated by Django 4.0.dev20210713072537 on 2021-08-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='English_word',
            field=models.CharField(max_length=30),
        ),
    ]
