# Generated by Django 4.0.dev20210713072537 on 2021-08-12 11:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_words_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='English_word',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='words',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2021, 8, 12, 11, 22, 23, 508080, tzinfo=utc)),
        ),
    ]
